# Generated by Django 3.1.3 on 2021-01-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, help_text='Ваше красивое фото', null=True, upload_to='forms/teachers', verbose_name='Фото'),
        ),
    ]
